### ISSUE TITLE
aws/local: Add a choice to preserve gitops/metaphor repos on destroy

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1039]
# Challenge

- [ ] Add a flag to allow gitops to not be removed on a cluster destroy(on git provider)
- [ ] Add a flag to allow metaphor-x to not be deleted on a cluster destroy(on git provider)
- [ ] How to be able to recycle on install repos on a re-install scenario. 

# Caveats

-  Some detoken values may change, how to address that situation. How to re-detoken properly.

**Comment by 6za** [comment]
Some possible scenarios, that it would be important to handle: 
- [ ] Disaster Recovery: how to use existing gitops repo as blue-print to a new instance to recover the environment. 

- [ ] Some trick infra upgrades scenarios where the host machines are physically upgraded.

**Comment by pagottoo** [comment]
Following...

**Comment by fharper** [comment]
The destroying process is now using a manual deprovisioning for the UI installation, and will also for CLI installation with v2.3 as it will use the API instead of specific CLI code, so this won't be valid anymore. If an user wants to keep the repositories, they just have to NOT run [the Terraform git step](https://docs.kubefirst.io/next/civo/deprovision#git).
