### ISSUE TITLE
[QA/Release] Local - Validation for release

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst#1214]
# Actions

- [ ] Verify if local was impacted by release changes, any breaking change?
- [ ] Verify if local was impacted by release changes, any change of behavior? 
- [ ] Verify if local was impacted by release changes, any new bug? 

AC:
- [ ] 1 - Evidences of testing local
- [ ] 2 - Installation recording+testing
- [ ] 3 - Doc updates if found divergences

**Comment by converge** [comment]
Ticket assessed, bigger identified issued was related to ngrok, there were a possibility that it was caused by memory leak that I addressed here https://github.com/kubefirst/kubefirst/pull/1228

ngrok team assessed Kubefirst implementation reported no issue, but a service down report that doesn't match the day we were having the issue. ngrok ticket is closed, and will be open if the issue happen again.
