### ISSUE TITLE
kubefirst k3d platform does not work with rancher desktop

### ISSUE THREAD

**Issue by jarededwards** [kubefirst/kubefirst#1514]
**What would you like to be added**:
rancher desktop support for the kubefirst k3d platform

**Why is this needed**:
rancher desktop is a popular docker desktop replacement and GUI for manging containers and we should be able to support multiple conatiner desktop tools for user support.

**Comment by Claywd** [comment]
## So current state.....

### WSL

We run k3d with `--agents 3` and `--agents-memory 1024m` flags. 

The `--agents 3` flag results in extremely slow response times from k3d and makes it time out essentially but the cli never exits. It just hangs. 
![image](https://github.com/kubefirst/kubefirst/assets/6446939/d3fed649-6da7-42f4-b0a3-e08a6b5eee91)

Issue tracking this is here https://github.com/k3d-io/k3d/issues/797 

The `--agents-memory 1024m` flag results in an OCI runtime error where the container literally fails to create, probably for lack of disk space when trying to map memory for the containers. 

Error here 
```
Failed Cluster Start: Failed to add one or more agents: runtime failed to start node 'k3d-kubefirst-agent-0': docker failed to start container for node 'k3d-kubefirst-agent-0': Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/wsl/rancher-desktop/run/docker-mounts/47932a34-5fca-40ff-a362-60f6c125e970" to rootfs at "/proc/meminfo": mount /mnt/wsl/rancher-desktop/run/docker-mounts/47932a34-5fca-40ff-a362-60f6c125e970:/proc/meminfo (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 
```

tracking this issue here https://github.com/rancher-sandbox/rancher-desktop/issues/4748

Additionally, other errors pop up randomly, usually related to networking and IP addresses. 
```ERRO[0000] error getting loadbalancer config from k3d-kubefirst-serverlb: runtime failed to read loadbalancer config '/etc/confd/values.yaml' from node 'k3d-kubefirst-serverlb': Error response from daemon: Could not find the file /etc/confd/values.yaml in container 6e46a10efb7f3a4751ef6535d45cde25ef0400335681af57de4736be54471014: file not found ```

Haven't opened an issue because we can't really get far enough to detect if this is a real issue. 

### Workaround. 

drop the `agents-memory` flag and `agents` flag and rebuild the source or just create the cluster before you run kubefirst cli with 

```
/root/.k1/kubefirst/tools/k3d cluster create kubefirst --image rancher/k3s:v1.26.3-k3s1 --registry-create k3d-kubefirst-registry --volume /root/.k1/kubefirst/minio-storage:/var/lib/rancher/k3s/storage@all --port 443:443@loadbalancer --verbose
```
if you are working off main or 

```
/root/.k1/kubefirst/tools/k3d cluster create kubefirst --image rancher/k3s:v1.26.3-k3s1 --registry-create k3d-kubefirst-registry --port 443:443@loadbalancer
```

 . This will make everything extremely slow. It'll make dial up seem like fiber but it will work. 



## MacOS 

This hit other erros mostly related to contacting the deamon.

**Comment by EamonKeane** [comment]
Just to note that I have this working with rancher desktop (v1.9.0) on the Mac M1. The config I used was:

* Ensure that docker desktop is not running and `/var/run/docker.sock` is symlinked to `~/.rd/docker.sock=`
* Disable traefik for the default kubernetes installation (it appears to interfere with the k3d proxy). When traefik was enabled, 127.0.0.1:443 was getting 404 and not working due to the presence of the default `TRAEFIK DEFAULT CERT` presumably from the default non-k3d traefik.
* For configuration use `dockerd (moby)` for the container engine, `virtiofs` for the volume, `VZ` Apple virtualization framework with Rosetta. This combination will give close to native speed.

**Comment by Claywd** [comment]
@EamonKeane That's great news! 

Is metaphor deploying as expected with that setup? You can check the piplines in gitlab or actions in github to check. You can also hit me up in kubefirst.slack.com to chat through some specifics.

**Comment by EamonKeane** [comment]
@Claywd yea everything works fine!

I was trying to also install gitlab omnibus with sets the sticky bit '2770' on certain directories but that wasn't working. It worked on earlier versions of rancher (outside of k3d) so not sure what the difference there is. But all the other volumes for kubefirst work without an issue.

**Comment by Claywd** [comment]
Adding this issue for wsl to track support for rancher desktop via nerdctl in wsl2. https://github.com/rancher-sandbox/rancher-desktop/issues/5079

**Comment by fharper** [comment]
@EamonKeane seems like you made it work, so I'll close this issue. Let us know if it's not the case.
