### ISSUE TITLE
[Feature] Allow users to add gitops catalog apps from the CLI

### ISSUE THREAD

**Issue by ShankyJS** [kubefirst/kubefirst#1743]
### What is your feature idea?

At the moment, Kubefirst has a great catalog to choose from various tools. However, this is only visible through the UI, 

For users like me who prefer to use a CLI, the GitOps catalog is unavailable.

Can we add support to it?

### Why is it needed?

- Enable users to deploy apps from the catalog by using the CLI
- Allow these apps manipulation from CI, which is more automation-friendly than a UI.

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Thanks a lot @ShankyJS for this suggestion. This is something we had in mine already, but forgot to create the proper feature request issue for it!

**Comment by fharper** [comment]
So, the first part of this request is done, meaning that now the GitOps catalog is now available on the management cluster. Previously, it was only on cluster 0, which existed only when using the UI to create a new cluster.

With that said, this issue is also about installing applications using the CLI, and not the catalog UI. This part isn't done. Still with v2.3 release, we revamped the CLI to use the API (instead of having the business logic duplicated-ish in the CLI code base) so it's gonna be easier to implement.

It should be the case of adding a new command to the CLI with some flags.

**Comment by johndietz** [comment]
You can currently install applications on the k3d platform using the console application. We would like to extend this ability to a cli flag that we'd like to add to the `kubefirst k3d create` command.

The new flag being proposed will be `--catalog` that could receive a comma delimited list of catalog apps to add. The order may be important to the end user for interdependency reasons and should probably be honored in sequence left to right if that doesn't introduce a lot of complexity.

example proposed command
`kubefirst k3d create --catalog=kratix,flappy-kray`

**Comment by ShankyJS** [comment]
This sounds amazing @johndietz probably it would be worth to also allow the user to install apps after running the `kubefirst k3d create` perhaps `kuberfirst catalog install [array of apps]`

I would love to at least do a PoC implementation for this one, what would be some good first steps to have this running?

Thanks
