### ISSUE TITLE
Map created resources

### ISSUE THREAD

**Issue by marinhojess** [kubefirst/kubefirst#346]
When installing a cluster through Kubefirst, some resources are created, see list below:

- VPC
- EC2/Load Balancer
- S3 Buckets
- KMS
- KMS Alias
- EKS Cluster
- Volumes
- EC2 Instances
- Routes from Route53
- DynamoDB
- IAM Roles
- IAM Policies
- ECR

For a better management of resources, it is necessary to create a binary using Golang to verify if these resources were created correctly in the cloud (The cloud API and the Terraform tfstate file can be used in this step).

The binary should generate a list of all the resources that were actually created and store this in a file.

**Comment by marinhojess** [comment]
Hi @Adidev-KGP,

I created this issue as the first step towards completing issue #308, I think it's a great start for you to contribute with us.

We're working on Github access issues, but you can start working on it as soon as you like.
It's worth mentioning that creating the cluster will incur charges on AWS, so it's a good tip to always destroy your cluster as soon as you finish your tests.

Please, if you have any questions, let us know, we will be happy to help you. :smile: 

Thanks again for your interest in Kubefirst, have fun! :rocket:

**Comment by Adidev-KGP** [comment]
Thank you so much @marinhojess . I'll start working on this issue.

Also, I want to mention that I have used cloud-radar (https://github.com/DontShaveTheYak/cloud-radar) which is an open source tool and is kind of a wrapper over taskcat which can be used to unit-test CloudFormation templates without creating the stack on AWS and it(cloud-radar) does the similar thing of producing the list of resources to be created without deploying it actually on AWS.

I have written an article to explain how to unit-test CloudFormation templates without deploying them on AWS and my article  covers how to use cloud-radar as well. 
Here is the link  - https://fallacious-address-6ff.notion.site/Testing-AWS-CF-template-a8ded41ffb0c4101810b25a1800b4c4a

The idea of this issue is kind of similar and I am really excited to work on it.

**Comment by Adidev-KGP** [comment]
@marinhojess  is it possible to create the cluster on AWS free tier account? I do not have a credit card 😢
