### ISSUE TITLE
[Docs]: Update roadmap for 1.11

### ISSUE THREAD

**Issue by fharper** [kubefirst/kubefirst#802]
We need to update the [roadmap](https://docs.kubefirst.io/roadmap/index.html) to reflect the changes and fixes we plan to do with the release of 1.11

**Comment by wolfskaempf** [comment]
Thank you for creating `kubefirst`! ✨ I would be especially interested in learning more about plans to support other providers (e.g. DigitalOcean, OVH, Hetzner) as deployment-targets and how such plans (if any) would align with the roadmap. Thank you!

**Comment by jarededwards** [comment]
hi @wolfskaempf thanks for checking out kubefirst! We're currently in the process of adopting Civo's cloud but are refactoring some of our components to make it easier to adopt others. Digital Ocean and GCP are high on our priority list from requests from our community users - would Digital Ocean be suitable for your needs?

**Comment by wolfskaempf** [comment]
Thank you for already answering here in the comments! 

For my personal needs, DigitalOcean is perfectly sufficient and due to its low-cost barrier of entry would allow me to use GitOps for my personal projects without breaking the bank.

At work we have some cases where we require a German provider like Hetzner or at least a European provider like OVH for regulatory reasons, hence why I asked about those three, but I do of course understand that German regulatory edge cases don't make it into your priority list.

Thank you and I'm looking forward to 1.11!
